name: LangVis
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - captum=0.5.0=0
  - numpy=1.19.2=py37hadc3359_0
  - numpy-base=1.19.2=py37ha3acd2a_0
  - torchvision=0.9.1=py37_cu102
  - tqdm=4.62.3=pyhd8ed1ab_0
  - pip:
    - diffusers==0.2.4
    - flask==2.2.2
    - flask-sqlalchemy==3.0.2
    - tokenizers==0.12.1
    - transformers==4.21.2
    - werkzeug==2.2.2
